### ISSUE TITLE
mysql catalog does not handle uppercase tablenames

### ISSUE THREAD

**Issue by tooptoop4** [Netflix/metacat#292]
#mysql table s3.source works
curl -X GET --header 'Accept: application/json' 'http://dns:8088/metacat-1.1.1/mds/v1/catalog/mysql-56-db/database/s3/table/source?includeInfo=true&includeDefinitionMetadata=true&includeDataMetadata=true'

#mysql table metastore.DBS error (trying curl with DBS or dbs both give error)
curl -X GET --header 'Accept: application/json' 'http://dns:8088/metacat-1.1.1/mds/v1/catalog/mysql-56-db/database/metastore/table/DBS?includeInfo=true&includeDefinitionMetadata=true&includeDataMetadata=true'

2018-09-13 02:09:59.700 ERROR 60262 --- [nio-8088-exec-1] c.n.metacat.main.api.ExceptionMapper     : Unable to locate for mysql-56-db/metastore/dbs. Details: TABLE 'mysql-56-db/metastore/dbs' not found.
com.netflix.metacat.common.exception.MetacatNotFoundException: Unable to locate for mysql-56-db/metastore/dbs. Details: TABLE 'mysql-56-db/metastore/dbs' not found.
        at com.netflix.metacat.main.api.RequestWrapper.processRequest(RequestWrapper.java:125) ~[metacat-main-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]
        at com.netflix.metacat.main.api.v1.MetacatController.getTable(MetacatController.java:640) ~[metacat-main-1.2.0-SNAPSHOT.jar:1.2.0-SNAPSHOT]

**Comment by karthik1289** [comment]
Created PR for this problem: https://github.com/Netflix/metacat/pull/340
