### ISSUE TITLE
unable to git clone permission denied

### ISSUE THREAD

**Issue by jojoho921** [Netflix/metacat#320]
Trying to clone the git repo and get the permission denied error. How can get access? 

git clone git@github.com:Netflix/metacat.git
Cloning into 'metacat'...
The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by zhljen** [comment]
Can you follow up the github [instruction](https://help.github.com/articles/error-permission-denied-publickey/) to setup your key?

**Comment by jojoho921** [comment]
Thanks. It worked after setting the public key. Now it failed at the gradle build with the error at task :metacat-common:compileJava while configure the project saying lombok.javac.apt.LombokProcessor could not be initialized. I used java 1.8 do i need a newer version? maybe there is something else I need to setup as prerequisite? Readme does not say anything. Please advise. Thanks.
 
```
> Task :metacat-common:compileJava FAILED
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/DataMetadataDto.java:37: warning: lombok.javac.apt.LombokProcessor could not be initialized. Lombok will not run during this compilation: java.lang.IllegalArgumentException: com.sun.tools.javac.api.ClientCodeWrapper$WrappedStandardJavaFileManager extends com.sun.tools.javac.api.ClientCodeWrapper$WrappedJavaFileManager implements javax.tools.StandardJavaFileManager
public class DataMetadataDto extends BaseDto implements HasDataMetadata {
       ^
        at lombok.javac.apt.LombokFileObjects.getCompiler(LombokFileObjects.java:130)
        at lombok.javac.apt.InterceptingJavaFileManager.<init>(InterceptingJavaFileManager.java:40)
        at lombok.javac.apt.LombokProcessor.placePostCompileAndDontMakeForceRoundDummiesHook(LombokProcessor.java:164)
        at lombok.javac.apt.LombokProcessor.init(LombokProcessor.java:85)
        at lombok.core.AnnotationProcessor$JavacDescriptor.want(AnnotationProcessor.java:87)
        at lombok.core.AnnotationProcessor.init(AnnotationProcessor.java:140)
        at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.init(AnnotationProcessor.java:69)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:674)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:771)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:866)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2100(JavacProcessingEnvironment.java:110)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1202)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1311)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1250)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:928)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:35)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:98)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:51)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:39)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:207)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:133)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.base/java.lang.Thread.run(Thread.java:844)
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/DataMetadataDto.java:37: error: DataMetadataDto is not abstract and does not override abstract method setDataMetadata(ObjectNode) in HasDataMetadata
public class DataMetadataDto extends BaseDto implements HasDataMetadata {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/json/MetacatJsonLocator.java:43: error: MetacatJsonLocator is not abstract and does not override abstract method getPrettyObjectMapper() in MetacatJson
public class MetacatJsonLocator implements MetacatJson {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/DefinitionMetadataDto.java:37: error: DefinitionMetadataDto is not abstract and does not override abstract method setDefinitionMetadata(ObjectNode) in HasDefinitionMetadata
public class DefinitionMetadataDto extends BaseDto implements HasDefinitionMetadata {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/QualifiedName.java:256: error: cannot find symbol
            partitionDto.getName().getPartitionName()
                        ^
  symbol:   method getName()
  location: variable partitionDto of type PartitionDto
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/PartitionDto.java:46: error: PartitionDto is not abstract and does not override abstract method setDataMetadata(ObjectNode) in HasDataMetadata
public class PartitionDto extends BaseDto implements HasDataMetadata, HasDefinitionMetadata {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/PartitionDto.java:70: error: cannot find symbol
        final String uri = serde != null ? serde.getUri() : null;
                                                ^
  symbol:   method getUri()
  location: variable serde of type StorageDto
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/PartitionDto.java:86: error: cannot find symbol
        return serde != null && serde.getUri() != null && !serde.getUri().isEmpty();
                                     ^
  symbol:   method getUri()
  location: variable serde of type StorageDto
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/PartitionDto.java:86: error: cannot find symbol
        return serde != null && serde.getUri() != null && !serde.getUri().isEmpty();
                                                                ^
  symbol:   method getUri()
  location: variable serde of type StorageDto
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/DatabaseDto.java:43: error: DatabaseDto is not abstract and does not override abstract method setDefinitionMetadata(ObjectNode) in HasDefinitionMetadata
public class DatabaseDto extends BaseDto implements HasDefinitionMetadata {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/CatalogDto.java:41: error: CatalogDto is not abstract and does not override abstract method setDefinitionMetadata(ObjectNode) in HasDefinitionMetadata
public class CatalogDto extends BaseDto implements HasDefinitionMetadata {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/CreateCatalogDto.java:39: error: CreateCatalogDto is not abstract and does not override abstract method setDefinitionMetadata(ObjectNode) in HasDefinitionMetadata
public class CreateCatalogDto extends BaseDto implements HasDefinitionMetadata {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/TableDto.java:51: error: TableDto is not abstract and does not override abstract method setDataMetadata(ObjectNode) in HasDataMetadata
public class TableDto extends BaseDto implements HasDataMetadata, HasDefinitionMetadata {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/TableDto.java:79: error: cannot find symbol
        final String uri = serde != null ? serde.getUri() : null;
                                                ^
  symbol:   method getUri()
  location: variable serde of type StorageDto
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/TableDto.java:109: error: cannot find symbol
                keys.add(field.getName());
                              ^
  symbol:   method getName()
  location: variable field of type FieldDto
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/TableDto.java:126: error: cannot find symbol
        return serde != null && serde.getUri() != null && !serde.getUri().isEmpty();
                                     ^
  symbol:   method getUri()
  location: variable serde of type StorageDto
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/dto/TableDto.java:126: error: cannot find symbol
        return serde != null && serde.getUri() != null && !serde.getUri().isEmpty();
                                                                ^
  symbol:   method getUri()
  location: variable serde of type StorageDto
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/TypeSignature.java:189: error: cannot find symbol
        final StringBuilder typeName = new StringBuilder(base.getType());
                                                             ^
  symbol:   method getType()
  location: variable base of type TypeEnum
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/DecimalType.java:36: error: DecimalType is not abstract and does not override abstract method getTypeSignature() in Type
public final class DecimalType extends AbstractType implements ParametricType {
             ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/RowType.java:41: error: RowType is not abstract and does not override abstract method getTypeSignature() in Type
public class RowType extends AbstractType implements ParametricType {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/RowType.java:63: error: cannot find symbol
                                return input == null ? null : input.getType();
                                                                   ^
  symbol:   method getType()
  location: variable input of type RowField
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/RowType.java:74: error: cannot find symbol
                            return input == null ? null : input.getName();
                                                               ^
  symbol:   method getName()
  location: variable input of type RowField
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/RowType.java:135: error: cannot find symbol
            result.add(field.getType());
                            ^
  symbol:   method getType()
  location: variable field of type RowField
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/TypeRegistry.java:108: error: cannot find symbol
        for (TypeSignature parameter : signature.getParameters()) {
                                                ^
  symbol:   method getParameters()
  location: variable signature of type TypeSignature
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/TypeRegistry.java:116: error: cannot find symbol
        final ParametricType parametricType = parametricTypes.get(signature.getBase());
                                                                           ^
  symbol:   method getBase()
  location: variable signature of type TypeSignature
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/TypeRegistry.java:121: error: cannot find symbol
            signature.getLiteralParameters());
                     ^
  symbol:   method getLiteralParameters()
  location: variable signature of type TypeSignature
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/CharType.java:35: error: CharType is not abstract and does not override abstract method getTypeSignature() in Type
public class CharType extends AbstractType implements ParametricType {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/VarcharType.java:33: error: VarcharType is not abstract and does not override abstract method getTypeSignature() in Type
public final class VarcharType extends AbstractType implements ParametricType {
             ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/MapType.java:34: error: MapType is not abstract and does not override abstract method getTypeSignature() in Type
public class MapType extends AbstractType implements ParametricType {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/MapType.java:70: error: cannot find symbol
        return ImmutableList.of(getKeyType(), getValueType());
                                ^
  symbol:   method getKeyType()
  location: class MapType
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/MapType.java:70: error: cannot find symbol
        return ImmutableList.of(getKeyType(), getValueType());
                                              ^
  symbol:   method getValueType()
  location: class MapType
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/VarbinaryType.java:31: error: VarbinaryType is not abstract and does not override abstract method getTypeSignature() in Type
public final class VarbinaryType extends AbstractType implements ParametricType {
             ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/BaseType.java:28: error: BaseType is not abstract and does not override abstract method getTypeSignature() in Type
public class BaseType extends AbstractType {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/ArrayType.java:32: error: ArrayType is not abstract and does not override abstract method getTypeSignature() in Type
public class ArrayType extends AbstractType implements ParametricType {
       ^
/Users/joanne/Development/metacat/metacat-common/src/main/java/com/netflix/metacat/common/type/ArrayType.java:72: error: cannot find symbol
        return ImmutableList.of(getElementType());
                                ^
  symbol:   method getElementType()
  location: class ArrayType
34 errors
1 warning```

**Comment by zhljen** [comment]
JDK 1.8 is correct. Please further verify your JDK setting. There's some discussion [here](https://stackoverflow.com/questions/47473770/lombok-javac-apt-lombokprocessor-could-not-be-initialized).

**Comment by zhljen** [comment]
We are using jdk 8, and my JVM  is 1.8.0_191. The command from the doc should work, and I will post you if I find anything else.

**Comment by jojoho921** [comment]
Finally I can successfully build metacat. Can you share how/where to setup those two basic configurations?
