### ISSUE TITLE
Start with NucleusUserException when use metacat-app.jar

### ISSUE THREAD

**Issue by zhoukangcn** [Netflix/metacat#416]
You can reproduce this problem as follow:
- add a embedded Hive catalog with config `javax.jdo.*`
-  Start service with `java -jar metacat-app.*.jar`

You will get this error:
```
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.jdo.JDOHelper$16.run(JDOHelper.java:1965)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.jdo.JDOHelper.invoke(JDOHelper.java:1960)
	at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1166)
	... 90 more
Caused by: org.datanucleus.exceptions.NucleusUserException: Error : Could not find API definition for name "JDO". Perhaps you dont have the requisite datanucleus-api-XXX jar in the CLASSPATH?
	at org.datanucleus.api.ApiAdapterFactory.getApiAdapter(ApiAdapterFactory.java:94)
	at org.datanucleus.AbstractNucleusContext.<init>(AbstractNucleusContext.java:115)
	at org.datanucleus.PersistenceNucleusContextImpl.<init>(PersistenceNucleusContextImpl.java:165)
	at org.datanucleus.PersistenceNucleusContextImpl.<init>(PersistenceNucleusContextImpl.java:154)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.<init>(JDOPersistenceManagerFactory.java:419)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.createPersistenceManagerFactory(JDOPersistenceManagerFactory.java:308)
	at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManagerFactory(JDOPersistenceManagerFactory.java:217)
	at com.netflix.metacat.connector.hive.client.embedded.HivePersistenceManagerFactory.getpersistencemanagerfactory(HivePersistenceManagerFactory.java:97)
	at com.netflix.metacat.connector.hive.client.embedded.HivePersistenceManagerFactory.getPersistenceManagerFactory(HivePersistenceManagerFactory.java:60)
```

**Comment by zhoukangcn** [comment]
This problem can be repaired as follows:
https://stackoverflow.com/questions/37484239/apache-spark-hive-executable-jar-with-maven-shade
